[tools]
atuin = "latest"
"aqua:exercism/cli" = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:iawia002/lux" = "latest"
"aqua:microsoft/edit" = "latest"
"aqua:nats-io/natscli" = "latest"
"aqua:nushell/nushell" = "latest"
"aqua:peteretelej/tree" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"aqua:twistedpair/google-cloud-sdk" = "latest"
"aqua:zyedidia/micro" = "latest"
"aqua:Wilfred/difftastic" = "latest"
bat = "latest"
bottom = "latest"
bun = "latest"
carapace = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
cmake = "latest"
conan = "latest"
crush = "latest"
delta = "latest"
dust = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
"github:danielmiessler/fabric" = "latest"
"github:xmake-io/xmake" = "latest"
go = "latest"
hyperfine = "latest"
node = "latest"
"npm:@jetbrains/junie-cli" = "latest"
"npm:@kilocode/cli" = "latest"
"npm:@sourcegraph/amp" = "latest"
odin = "latest"
opencode = "latest"
"pipx:tldr" = "latest"
python = "latest"
ripgrep = "latest"
sd = "latest"
sqlite = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yt-dlp = "latest"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = true
  
[settings.npm]
bun = true
package_manager = "bun"

[settings.python]
compile = false
